export const Category = Object.freeze({
    BMS_IC: 'BMS IC',
    Board: 'Board',
    Capacitor: 'Capacitor',
    Comparator: 'Comparator',
    Connector: 'Connector',
    Crimp: 'Crimp',
    Digital_Isolator: 'Digital Isolator',
    Diode: 'Diode',
    Fuse: 'Fuse',
    IC_Flash: 'IC Flash',
    Inductor: 'Inductor',
    Inverter: 'Inverter',
    LED: 'LED',
    Linear_Regulator: 'Linear Regulator',
    MCU: 'MCU',
    Mosfet: 'Mosfet',
    Multiplexer: 'Multiplexer',
    NAND: 'NAND',
    Opto_Isolator: 'Opto-Isolator',
    Oscillator: 'Oscillator',
    Pushbutton: 'Pushbutton',
    Relay: 'Relay',
    Resistor: 'Resistor',
    Sensor: 'Sensor',
    Shunt_Diode: 'Shunt Diode',
    Switching_Converter: 'Switching Converter',
    Switching_Regulator: 'Switching Regulator',
    Test_Point: 'Test Point',
    Thermistor: 'Thermistor',
    Timer_IC: 'Timer IC',
    Transceiver: 'Transceiver'
  });